LOGIN = "id:SignIn"
EMAIL_INPUT =" id:email-id"
PASSWORD_INPUT = "id:password"
SUBMIT_BUTTON= "css:button"
NEW_CUSTOMER = "id:new-customer"
EMAIL_CUS = "id:EmailAddress"
FN_CUS = "id:FirstName"
LN_CUS = "id:LastName"
CITY = "id:City"
STATE = "css:select"
GENDER= "xpath=//input[@name='gender']"
PROMO= "xpath=//input[@value='promos-yes']"
SUBMIT_CUS= "css:button"
REMEMBER = "id:remember"
LOGOUT ="xpath=//a[@href='sign-out.html']"
LOGIN_2 = "xpath=//a[@href='login.html']"
CANCEL= "xpath=//a[@href='customers.html']"   


